Repository mindsphere/mindconnect-nodejs, pull requests merged in 2020-10, with the labels that each got.

#183 fix: fixed the help output #182
  src/cli/commands/identity.ts
Labels: bug, hacktoberfest-accepted

#186 Update: added binary versions of the command line interface for windows, macos and linux
  .gitignore
  .npmignore
  package-lock.json
  package.json
Labels: enhancement, hacktoberfest-accepted

#187 fix: powershell npm install #184
  package-lock.json
  package.json
Labels: bug, hacktoberfest-accepted

#188 chore : updated changelog, updated version
  CHANGELOG.md
  package-lock.json
  package.json
  src/api/mindconnect-base.ts
  src/cli/commands/html/sc/index.html
Labels: chore

#189 chore: bumped dependencies
  CHANGELOG.md
  package-lock.json
  package.json
  src/api/mindconnect-base.ts
  src/cli/commands/mc-version-help.ts
  src/index.ts
  src/version.ts
Labels: chore

#191 feat: CLI: notify users if there is a new version of the CLI available
  package-lock.json
  package.json
  src/cli/commands/mc-version-help.ts
Labels: enhancement, hacktoberfest-accepted

#195 feat: add the digital twin type option to create-asset command
  src/cli/commands/create-asset.ts
Labels: hacktoberfest-accepted

#196 chore: 3.9.0-2 alpha release
  CHANGELOG.md
  package-lock.json
  package.json
  src/cli/commands/analyze-events.ts
  src/cli/commands/aspect-commands.ts
  src/cli/commands/asset-types.ts
  src/cli/commands/assets.ts
  src/cli/commands/create-asset.ts
  src/cli/commands/delete-asset.ts
  src/cli/commands/download-events.ts
  src/cli/commands/mc-list-assets.ts
  src/cli/commands/mc-service-credentials.ts
  src/cli/mc.ts
Labels: enhancement

#212 feat: unitests are runnable on all instances (prod-a , prod-b, ...)
  CHANGELOG.md
  Jenkinsfile
  src/api/sdk/event/event-management.ts
  test/agent-auth.spec.ts
  test/credential-auth.spec.ts
  test/mindconnect-agent-3.spec.ts
  test/mindconnect-agent-autoconfig.spec.ts
Labels: chore

#213 chore: set of tests for s4f and sanity checks
  CHANGELOG.md
  CONTRIBUTING.md
  Jenkinsfile
  package-lock.json
  package.json
  test/agent-auth.spec.ts
  test/agent-management.spec.ts
  test/asset-management-aspecttypes.spec.ts
  test/asset-management-assets.spec.ts
  test/asset-management-assetypes.spec.ts
  test/asset-management-files.spec.ts
  test/credential-auth.spec.ts
  test/identity-management.spec.ts
  test/iot-file.spec.ts
  test/iot-ts-aggregates.spec.ts
  test/mindconnect-agent-3-rsa.spec.ts
  test/mindconnect-storage.spec.ts
  test/sdk-auth-test.spec.ts
  test/signal-validation.spec.ts
  test/tokenmanager-auth.spec.ts
Labels: chore, hacktoberfest-accepted

#217 feat: add support for direct interaction to KPI Calculation Client
  src/api/sdk/kpi/kpi.ts
Labels: hacktoberfest-accepted

#218 feat: add support for direct interaction with TimeSeries Data to TrendPrediction Client
  CHANGELOG.md
  src/api/sdk/trend/trend-prediction-models.ts
  src/api/sdk/trend/trend-prediction.ts
Labels: hacktoberfest-accepted
